replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 50Mi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: recipes.stewartplatt.com
    paths:
    - '/'
  - host: www.recipes.stewartplatt.com
    paths:
    - '/'
  tls:
  - secretName: recipes-stewartplatt-com
    hosts:
    - recipes.stewartplatt.com
    - www.recipes.stewartplatt.com
